--- #YAML:1.0
name:               Gtk2-Ex-QuadButton
version:            1
abstract:           Widget for four arrow directions.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Glib::Object::Subclass:  0
    Gtk2:                 1.220
    Gtk2::Ex::AdjustmentBits:  40
    Gtk2::Ex::Units:      13
    Gtk2::Ex::WidgetBits:  40
    perl:                 5.008
resources:
    homepage:  http://user42.tuxfamily.org/gtk2-ex-quadbutton/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - xt
        - devel
        - examples
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_devel:
        description:  Stuff used variously for development.
        requires:
            Glib::Ex::ConnectProperties:  0
            Gtk2::Ex::ComboBox::Enum:  0
            Pod::Simple::HTML:    0
            Smart::Comments:      0
            warnings::unused:     0
    maximum_interoperation:
        description:  Have maximum inter-operation with other modules (optional other stuff).
        requires:
            Locale::Messages:  0
    maximum_tests:
        description:  Have "make test" do as much as possible.
        requires:
            Parse::CPAN::Meta:   0
            Test::DistManifest:  0
            Test::Pod:           1.00
            Test::Synopsis:      0
            Test::Weaken:        3
            Test::Weaken::Gtk2:  0
            Test::YAML::Meta:    0.15
            YAML:                0
            YAML::Syck:          0
            YAML::Tiny:          0
            YAML::XS:            0
